name: weather_app
description: "A simple location based weather smart watch app."
publish_to: 'none'
version: 1.0.5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  http: ^1.5.0
  wear_plus: ^1.2.3
  location: ^4.3.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dart_pre_commit: ^6.0.0
  git_hooks: ^1.0.2

flutter:
  assets:
    - .env
  uses-material-design: true
